services:
  materialize:
    image: materialize/materialized:v0.9.13
    volumes:
      - "/host/code/sproutfi/redpanda-repro/materialize:/views"
    depends_on:
      - redpanda
  redpanda:
    image: vectorized/redpanda:v21.9.6
    command:
      - "redpanda start"
      - "--smp 1"
      - "--overprovisioned"
      - "--set redpanda.auto_create_topics_enabled=true"
      - "--set redpanda.enable_idempotence=true"
      - "--set redpanda.enable_transactions=true"
      - "--set redpanda.id_allocator_replication=1"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://redpanda:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
  benthos:
    image: jeffail/benthos:3.58
    volumes:
      - "/host/code/sproutfi/redpanda-repro/benthos:/etc/benthos"
    command:
      - "-c"
      - "/etc/benthos/config.yaml"
    depends_on:
      - redpanda
  postgresql:
    image: postgres
    volumes:
      - "/host/code/sproutfi/redpanda-repro/materialize:/views"
    command:
      - "sh"
      - "-c"
      - |
        sleep 2
        echo here
        ls -al /views
        psql -U materialize -p 6875 -h materialize < /views/materialize.sql
    depends_on:
      - materialize
  write_stuff:
    image: busybox
    volumes:
      - "/host/code/sproutfi/redpanda-repro/materialize:/views"
    command:
      - "sh"
      - "-c"
      - |
        sleep 15
        # I don't think the tail is actually working though
        echo -ne '{"a":3,"b":5}\n{"a":15,"b":7}' >> /views/source.json
