http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
input:
  label: ""
  kafka:
    addresses:
      - redpanda:9092
    topics:
      - sometopic
    target_version: 1.0.0
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    sasl:
      mechanism: ""
      user: ""
      password: ""
      access_token: ""
      token_cache: ""
      token_key: ""
    consumer_group: benthos_consumer_group
    client_id: benthos_kafka_input
    rack_id: ""
    start_from_oldest: true
    checkpoint_limit: 1
    commit_period: 1s
    max_processing_period: 100ms
    extract_tracing_map: ""
    group:
      session_timeout: 10s
      heartbeat_interval: 3s
      rebalance_timeout: 60s
    fetch_buffer_cap: 256
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
      processors: []
buffer:
  none: {}
pipeline:
  threads: 1
  processors: []
output:
  label: ""
  stdout:
    codec: lines
logger:
  level: INFO
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
metrics:
  http_server:
    prefix: benthos
    path_mapping: ""
tracer:
  none: {}
shutdown_timeout: 20s